; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Mon May 07 2018 15:37:05 GMT+0200 (CEST)
M561 ; clear any bed transform
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y195 H0 Z-99999
G30 P2 X215 Y195 H0 Z-99999
G30 P3 X215 Y15 H0 Z-99999 S