; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Tue May 08 2018 14:10:05 GMT+0200 (CEST)
G91              ; relative positioning
G1 Z5 F600 S1   ; lift Z relative to current position
G1 S1 Y1400 F3200 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y-5 F600     ; go back a few mm
G1 S1 Y1400 F300  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F600  ; lower Z again
G90              ; absolute positioning